name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: "45 0 1 1,7 *"

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.vars.outputs.ref }}
      user: ${{ steps.vars.outputs.user }}
    steps:
      - name: "Set variables"
        id: vars
        run: |
          echo "ref=$GITHUB_REF" >> $GITHUB_OUTPUT
          echo "user=$GITHUB_ACTOR" >> $GITHUB_OUTPUT

  deploy:
    needs: [variables]
    uses: moogur/all-workflows/.github/workflows/deploy_for_docker_container.yml@master
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      event_name: ${{ github.event_name }}
      github_user: ${{ needs.variables.outputs.user }}
      ref: ${{ needs.variables.outputs.ref }}
