name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: "45 0 1 1,7 *"

jobs:
  deploy:
    steps:
      - name: "Set variables"
        id: variables
        run: |
          echo "ref=$GITHUB_REF" >> $GITHUB_OUTPUT

      - name: "Deploy"
        uses: moogur/all-workflows/.github/workflows/deploy_for_docker_container.yml@master
        secrets: inherit
        with:
          repository: ${{ github.event.repository.name }}
          github_user: ${{ github.event.actor.login }}
          event_name: ${{ github.event_name }}
          ref: ${{ steps.version.outputs.ref }}
