name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: "45 0 1 1,7 *"

jobs:
  deploy:
    uses: moogur/.github/workflows/deploy_for_docker_container.yml@master
    secrets: inherit
    with:
      repository: $GITHUB_REPOSITORY
      ref: $GITHUB_REF
      event_name: ${{ github.event_name }}
